'use strict';

// Events to players
const DISTRIBUTING_CARDS = 'DISTRIBUTING_CARDS';
const STORY_TELLER_IS = 'STORY_TELLER_IS';

const STORY_TELLERS_CARD = 'STORY_TELLERS_CARD';
const PLAYER_CARD = 'PLAYER_CARD';
const REVEAL_CARDS = 'REVEAL_CARDS';
const ENABLE_VOTING = 'ENABLE_VOTING';

const PLAYERS_VOTE = 'PLAYERS_VOTE';

module.exports = {
  DISTRIBUTING_CARDS,
  STORY_TELLER_IS,
  STORY_TELLERS_CARD,
  PLAYER_CARD,
  REVEAL_CARDS,
  ENABLE_VOTING,
  PLAYERS_VOTE,

};
